### ISSUE TITLE
Colmap Problem

### ISSUE THREAD

**Issue by ZhenyuSun-Walker** [RyanPham19092002/Rendering-novel-view-by-MVSGaussian#1]
Hello, I noticed that you 've met the same problem before, shown as below. Would you mind sharing your experience on how to tackle with this error?
 
Error :
Need to run COLMAP
qt.qpa.xcb: could not connect to display :0
qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: eglfs, linuxfb, minimal, minimalegl, offscreen, vnc, xcb.

*** Aborted at 1721114100 (unix time) try "date -d @1721114100" if you are using GNU date ***
PC: @ 0x7f5ad03cd00b gsignal
*** SIGABRT (@0x3fd00004a4a) received by PID 19018 (TID 0x7f5acbbc7900) from PID 19018; stack trace: ***
@ 0x7f5ad1fbb631 (unknown)
@ 0x7f5ad14fe420 (unknown)
@ 0x7f5ad03cd00b gsignal
@ 0x7f5ad03ac859 abort
@ 0x7f5ad0991aad QMessageLogger::fatal()
@ 0x7f5ad0f737ae QGuiApplicationPrivate::createPlatformIntegration()
@ 0x7f5ad0f74708 QGuiApplicationPrivate::createEventDispatcher()
@ 0x7f5ad0b98f55 QCoreApplicationPrivate::init()
@ 0x7f5ad0f76543 QGuiApplicationPrivate::init()
@ 0x7f5ad16803bd QApplicationPrivate::init()
@ 0x559014f0f602 RunFeatureExtractor()
@ 0x559014efbeaf main
@ 0x7f5ad03ae083 __libc_start_main
@ 0x559014efff6e _start
Traceback (most recent call last):
File "lib/colmap/imgs2poses.py", line 17, in
gen_poses(args.scenedir, args.match_type)
File "/data/Phat/MVSGaussian/lib/colmap/poses/pose_utils.py", line 268, in gen_poses
run_colmap(basedir, match_type)
File "/data/Phat/MVSGaussian/lib/colmap/poses/colmap_wrapper.py", line 35, in run_colmap
feat_output = ( subprocess.check_output(feature_extractor_args, universal_newlines=True) )
File "/home/vinai/.conda/envs/mvsgs/lib/python3.7/subprocess.py", line 411, in check_output
**kwargs).stdout
File "/home/vinai/.conda/envs/mvsgs/lib/python3.7/subprocess.py", line 512, in run
output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['colmap', 'feature_extractor', '--database_path', '/data/Phat/MVSGaussian/examples/scene1/database.db', '--image_path', '/data/Phat/MVSGaussian/examples/scene1/images', '--ImageReader.single_camera', '1']' died with <Signals.SIGABRT: 6>.

**Comment by RyanPham19092002** [comment]
Hi, 
For my experience, I installed COLMAP based on this link https://colmap.github.io/install.html, and the problem was fixed.

**Comment by ZhenyuSun-Walker** [comment]
Thank you for your timely suggestions! I 'll check it ASAP.
